### ISSUE TITLE
Try Web Scraping

### ISSUE THREAD

**Issue by Adatta1276** [Journ12-Journals/Journ-1-Social-studies#5]
Let's Try Web Scraping for this

**Comment by Adatta1276** [comment]
https://github.com/sab99r/Indian-States-And-Districts/blob/master/states-and-districts.json

**Comment by Adatta1276** [comment]
this is the latitude and longitude+district and hills names, but we need to find/make a JSON for the information part of it

**Comment by Genius398** [comment]
i think @Super45coder is doing it for America

**Comment by Adatta1276** [comment]
Ok 😃

**Comment by Super45coder** [comment]
Not here. Do this in the project.
________________________________
